compose:
  # Nginx http server bind port for download files and packages
  http_port: 8080
  # Registry host ip for add to /etc/hosts by domain
  registry_ip: 172.20.0.25
  # Registry domain for CRI runtime download image
  registry_domain: "kube.registry.local"
  # Auto generate self-signed certificate for registry domain
  generate_crt: true
  self_signed_cert: true
  # User and password for push image to registry
  registry_auth_user: "Username"
  registry_auth_password: "Password"

kubespray:
  # Kubernetes version by default, only support v1.20.6
  kube_version: v1.21.3
  # For deploy HA cluster you must configure a external apiserver access ip
  external_apiserver_access_ip: "127.0.0.1"
  # Set network plugin to calico with vxlan mode by default
  kube_network_plugin: "calico"
  # Set true to download and cache container
  download_container: false
  # Use nginx and registry as all resources
  offline_resources_enabled: true
  ## Container runtime
  ## docker for docker, crio for cri-o and containerd for containerd.
  container_manager: containerd
  # Now only support host because use containerd as CRI runtime
  etcd_deployment_type: host
  # Settings for etcd event server
  etcd_events_cluster_setup: true
  etcd_events_cluster_enabled: true
